export const ODS_LIST = [
  { numero: 1,  titulo: 'Erradicação da Pobreza', descricao: 'Acabar com a pobreza em todas as suas formas, em todos os lugares' },
  { numero: 2,  titulo: 'Fome Zero e Agricultura Sustentável', descricao: 'Acabar com a fome, alcançar a segurança alimentar e melhoria da nutrição e promover a agricultura sustentável' },
  { numero: 3,  titulo: 'Saúde e Bem-Estar', descricao: 'Assegurar uma vida saudável e promover o bem-estar para todos, em todas as idades' },
  { numero: 4,  titulo: 'Educação de Qualidade', descricao: 'Assegurar a educação inclusiva e equitativa de qualidade, e promover oportunidades de aprendizagem ao longo da vida para todos' },
  { numero: 5,  titulo: 'Igualdade de Gênero', descricao: 'Alcançar a igualdade de gênero e empoderar todas as mulheres e meninas' },
  { numero: 6,  titulo: 'Água Potável e Saneamento', descricao: 'Assegurar a disponibilidade e gestão sustentável da água e saneamento para todos' },
  { numero: 7,  titulo: 'Energia Limpa e Acessível', descricao: 'Assegurar o acesso confiável, sustentável, moderno e a preço acessível à energia, para todos' },
  { numero: 8,  titulo: 'Trabalho Decente e Crescimento Econômico', descricao: 'Promover o crescimento econômico sustentado, inclusivo e sustentável, emprego pleno e produtivo, e trabalho decente para todos' },
  { numero: 9,  titulo: 'Indústria, Inovação e Infraestrutura', descricao: 'Construir infraestruturas resilientes, promover a industrialização inclusiva e sustentável e fomentar a inovação' },
  { numero: 10, titulo: 'Redução das Desigualdades', descricao: 'Reduzir a desigualdade dentro dos países e entre eles' },
  { numero: 11, titulo: 'Cidades e Comunidades Sustentáveis', descricao: 'Tornar as cidades e os assentamentos humanos inclusivos, seguros, resilientes e sustentáveis' },
  { numero: 12, titulo: 'Consumo e Produção Responsáveis', descricao: 'Assegurar padrões de produção e de consumo sustentáveis' },
  { numero: 13, titulo: 'Ação Contra a Mudança Global do Clima', descricao: 'Tomar medidas urgentes para combater a mudança do clima e seus impactos' },
  { numero: 14, titulo: 'Vida na Água', descricao: 'Conservar e usar sustentavelmente os oceanos, os mares e os recursos marinhos para o desenvolvimento sustentável' },
  { numero: 15, titulo: 'Vida Terrestre', descricao: 'Proteger, recuperar e promover o uso sustentável dos ecossistemas terrestres, gerir de forma sustentável as florestas, combater a desertificação, deter e reverter a degradação da terra, e deter a perda de biodiversidade' },
  { numero: 16, titulo: 'Paz, Justiça e Instituições Eficazes', descricao: 'Promover sociedades pacíficas e inclusivas para o desenvolvimento sustentável, proporcionar o acesso à justiça para todos e construir instituições eficazes, responsáveis e inclusivas em todos os níveis' },
  { numero: 17, titulo: 'Parcerias e Meios de Implementação', descricao: 'Fortalecer os meios de implementação e revitalizar a parceria global para o desenvolvimento sustentável' },
] as const
